CREATE TABLE IF NOT EXISTS payment_orders (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  order_code VARCHAR(100) NOT NULL,
  provider ENUM('VNPAY') NOT NULL DEFAULT 'VNPAY',
  plan_code VARCHAR(50) NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  status ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  payment_url TEXT NULL,
  vnp_transaction_no VARCHAR(50) NULL,
  vnp_bank_code VARCHAR(30) NULL,
  vnp_bank_tran_no VARCHAR(100) NULL,
  vnp_card_type VARCHAR(30) NULL,
  vnp_response_code VARCHAR(10) NULL,
  vnp_transaction_status VARCHAR(10) NULL,
  raw_response TEXT NULL,
  expires_at DATETIME NOT NULL,
  paid_at DATETIME NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY payment_orders_order_code_key (order_code),
  UNIQUE KEY payment_orders_vnp_transaction_no_key (vnp_transaction_no),
  KEY payment_orders_user_status_idx (user_id, status, created_at),
  KEY payment_orders_expiry_idx (expires_at, status),
  CONSTRAINT payment_orders_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
